### PR TITLE
Prevent duplicate invites for existing memberships

### LINKED ISSUE #18: Duplicate groups being created for group owners
**Describe the bug**
Started a group, and received an email to join and also an invite.

**To Reproduce**
1. Start a new group
1. Specify my email address (as a member)
1. Receive welcome email
1. Go to Invites page
1. Accept invite

**Expected behavior**
> "You're already a member of this group"
> "Can't join a group you're already a member of"

or...idempotent/nothing happens.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by thestrabusiness**
Closes #18

This PR fixes an issue where group invites were being sent to existing
members of a group. Upon accepting the invite, an additional membership
record was being created for that user. This caused the group to appear
twice in the user's group list.

This commit adds validations around the creation of memberships and
invites. Users will no longer receive invites for groups they belong to
and it is no longer possible to create multiple membership records for
the same user.

### CODE REVIEW

File: app/models/group_invite.rb [hunk 1]
```diff
@@ -7,8 +7,16 @@ class GroupInvite < ApplicationRecord
...
   scope :unaccepted, -> { where(accepted: false) }
 
+  validate :user_not_already_in_group, on: :create
+
   private
 
+  def user_not_already_in_group
+    return unless group.users.where(email: email).exists?
+
+    errors.add(:group, "Can't send an invite to an existing member")
```
Comment (americanhanko) [inline app/models/group_invite.rb:17]: Do we bubble this error message up to the user who is creating the invite?

Comment (thestrabusiness) [reply app/models/group_invite.rb:17]: We don't, I'll add this. There are actually a few places in the application where we're not letting users know the success of failure of certain actions. I'll add an issue to cover that.
