### PR TITLE
Fix inconsistent date time display

### LINKED ISSUE #16: Calls are being created with an incorrect, inconsistent start time.
**Describe the bug**
Calls are being created with an incorrect start times. Groups have a default call time which calls should be scheduled with on creation.

Looking at the group details page, a call that should be scheduled at 4PM according to the groups `default_call_time`. The calls are being scheduled inconsistently.

Screen Shot 2020-04-05 at 12 24 40 PM

### PR DESCRIPTION
**Pull request by thestrabusiness**
Closes #16

This PR addresses two issues with the call times being displayed in a
few different places. Additionally, I refactored the DateFormatter to
DateTimeFormatter for a more accurate name.

Part of the issue was with the `strftime` calls being made in the
`DateTimeFormatter` using the wrong syntax.

Another issue was related to how calls were being created. The intention
was to use `Group#call_time` to set the `scheduled_on` attribute
of new calls, but the group attribute was never being used. This commit
fixes this issue as well.

### CODE REVIEW

File: app/services/date_time_formatter.rb [hunk 1]
```diff
@@ -1,20 +1,20 @@
...
   end
 
   def self.time_with_zone(datetime)
-    datetime.strftime("%l:%m %p %Z")
+    datetime.strftime("%l:%M %p %Z")
   end
 
   def self.time(datetime)
-    datetime.strftime("%l:%m %p")
+    datetime.strftime("%l:%M %p")
```
Comment (americanhanko) [inline app/services/date_time_formatter.rb:17]: Maybe we could use some attributes with friendly names to make the formats more readable and reduce the `datetime.strftime` repetition:

```ruby
private

@format_month_day = "%A, %B %e"
@format_time = "%l:%M %p"
@format_month_day_at_time = "#{@format_month_day} at #{@format_time_with_timezone}"
@format_time_with_timezone = "#{@format_time} %Z"

self.format_time(datetime, format)
  datetime.strftime(format)
end
```

Comment (thestrabusiness) [reply app/services/date_time_formatter.rb:17]: I'm not sure if I understand what you're going for here. Could you show me an example of how you'd use this?
